{
 "title": "Pi-Hole",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "PiholeDevices" },
   {
    "name": "JobName",
    "label": "JobName",
    "query": {
     "query": "label_values(pihole_status,job)"
    }
   },
   {
    "name": "Device",
    "query": {
     "query": "query_result(pihole_status{job=~'$JobName'})"
    }
   },
   {
    "name": "QueryTypes",
    "label": "QueryTypes",
    "query": {
     "query": "label_values(pihole_querytypes,type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_status", "legendFormat": "{{ legend }}" }
   ]
  },
  {
   "title": "Total Queries",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pihole_dns_queries_today{job=~'$JobName',instance=~'$Device'})",
     "legendFormat": "Total Queries"
    }
   ]
  },
  {
   "title": "Queries Blocked",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pihole_ads_blocked_today{job=~'$JobName',instance=~'$Device'})",
     "legendFormat": "Total Queries"
    }
   ]
  },
  {
   "title": "Percent Blocked",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pihole_ads_blocked_today{job=~'$JobName',instance=~'$Device'}) / sum(pihole_dns_queries_today{job=~'$JobName',instance=~'$Device'})",
     "legendFormat": "Total Queries"
    }
   ]
  },
  {
   "title": "Average of Domains in Blocklists",
   "type": "stat",
   "description": "This takes an average of all domains listed the Pihole servers you have selected.  If all your servers have the same number of blocked domains then this number should match.  If however you run 2 pihole servers where one server has 50 blocked domains and a second server has 100 blocked domains then it will show 75 (50+100)/2.",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(pihole_domains_being_blocked{job=~'$JobName',instance=~'$Device'})",
     "legendFormat": "Total Queries"
    }
   ]
  },
  {
   "title": "Total queries",
   "type": "graph",
   "description": "Because this graph does a delta between the current and previous 10 minutes it will take 20 minutes before you start seeing data.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(round(delta(pihole_ads_blocked_today{job=~'$JobName',instance=~'$Device'}[10m])))",
     "legendFormat": "Blocked"
    },
    {
     "expr": "sum(round(delta(pihole_queries_forwarded{job=~'$JobName',instance=~'$Device'}[10m])))",
     "legendFormat": "Permitted"
    }
   ]
  },
  {
   "title": "Client Activity",
   "type": "graph",
   "description": "Because this graph does a delta between the current and previous 10 minutes it will take 20 minutes before you start seeing data.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(round(delta(pihole_top_sources{job=~'$JobName',instance=~'$Device'}[10m]))) by (source)>0",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Query Types",
   "type": "piechart",
   "description": "The types shown here can be limited by updating the QueryTypes variable.  See the description for the variable for an example.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(pihole_querytypes{job=~'$JobName',instance=~'$Device',type=~'$QueryTypes'}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Queries Answered By",
   "type": "piechart",
   "description": "If you would like to set up or edit the colors you can edit this pane modify the overrides to match your  upstream DNS servers. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pihole_forward_destinations{job=~'$JobName',instance=~'$Device'}) by (destination,value)",
     "legendFormat": "{{destination}}"
    }
   ]
  },
  {
   "title": "Top Permitted Domains",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(pihole_top_queries{job=~'$JobName',instance=~'$Device'}) by (domain)"
    }
   ]
  },
  {
   "title": "Top Blocked Domains",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(pihole_top_ads{job=~'$JobName',instance=~'$Device'}) by (domain)"
    }
   ]
  },
  {
   "title": "Top Clients (total)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(pihole_top_sources{job=~'$JobName',instance=~'$Device'}) by (source)"
    }
   ]
  },
  {
   "title": "Pi-hole Server Information",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    { "expr": "pihole_status{job=~'$JobName'}" },
    {
     "expr": "pihole_domains_being_blocked{job=~'$JobName'}"
    }
   ]
  }
 ]
}